// Code generated by counterfeiter. DO NOT EDIT.
package flyfakes

import (
	"sync"

	"github.com/concourse/concourse-pipeline-resource/fly"
)

type FakeCommand struct {
	LoginStub        func(url string, teamName string, username string, password string, insecure bool) ([]byte, error)
	loginMutex       sync.RWMutex
	loginArgsForCall []struct {
		url      string
		teamName string
		username string
		password string
		insecure bool
	}
	loginReturns struct {
		result1 []byte
		result2 error
	}
	loginReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	PipelinesStub        func() ([]string, error)
	pipelinesMutex       sync.RWMutex
	pipelinesArgsForCall []struct{}
	pipelinesReturns     struct {
		result1 []string
		result2 error
	}
	pipelinesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetPipelineStub        func(pipelineName string) ([]byte, error)
	getPipelineMutex       sync.RWMutex
	getPipelineArgsForCall []struct {
		pipelineName string
	}
	getPipelineReturns struct {
		result1 []byte
		result2 error
	}
	getPipelineReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SetPipelineStub        func(pipelineName string, configFilepath string, varsFilepaths []string) ([]byte, error)
	setPipelineMutex       sync.RWMutex
	setPipelineArgsForCall []struct {
		pipelineName   string
		configFilepath string
		varsFilepaths  []string
	}
	setPipelineReturns struct {
		result1 []byte
		result2 error
	}
	setPipelineReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	DestroyPipelineStub        func(pipelineName string) ([]byte, error)
	destroyPipelineMutex       sync.RWMutex
	destroyPipelineArgsForCall []struct {
		pipelineName string
	}
	destroyPipelineReturns struct {
		result1 []byte
		result2 error
	}
	destroyPipelineReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	UnpausePipelineStub        func(pipelineName string) ([]byte, error)
	unpausePipelineMutex       sync.RWMutex
	unpausePipelineArgsForCall []struct {
		pipelineName string
	}
	unpausePipelineReturns struct {
		result1 []byte
		result2 error
	}
	unpausePipelineReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCommand) Login(url string, teamName string, username string, password string, insecure bool) ([]byte, error) {
	fake.loginMutex.Lock()
	ret, specificReturn := fake.loginReturnsOnCall[len(fake.loginArgsForCall)]
	fake.loginArgsForCall = append(fake.loginArgsForCall, struct {
		url      string
		teamName string
		username string
		password string
		insecure bool
	}{url, teamName, username, password, insecure})
	fake.recordInvocation("Login", []interface{}{url, teamName, username, password, insecure})
	fake.loginMutex.Unlock()
	if fake.LoginStub != nil {
		return fake.LoginStub(url, teamName, username, password, insecure)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.loginReturns.result1, fake.loginReturns.result2
}

func (fake *FakeCommand) LoginCallCount() int {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return len(fake.loginArgsForCall)
}

func (fake *FakeCommand) LoginArgsForCall(i int) (string, string, string, string, bool) {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return fake.loginArgsForCall[i].url, fake.loginArgsForCall[i].teamName, fake.loginArgsForCall[i].username, fake.loginArgsForCall[i].password, fake.loginArgsForCall[i].insecure
}

func (fake *FakeCommand) LoginReturns(result1 []byte, result2 error) {
	fake.LoginStub = nil
	fake.loginReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) LoginReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.LoginStub = nil
	if fake.loginReturnsOnCall == nil {
		fake.loginReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.loginReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) Pipelines() ([]string, error) {
	fake.pipelinesMutex.Lock()
	ret, specificReturn := fake.pipelinesReturnsOnCall[len(fake.pipelinesArgsForCall)]
	fake.pipelinesArgsForCall = append(fake.pipelinesArgsForCall, struct{}{})
	fake.recordInvocation("Pipelines", []interface{}{})
	fake.pipelinesMutex.Unlock()
	if fake.PipelinesStub != nil {
		return fake.PipelinesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.pipelinesReturns.result1, fake.pipelinesReturns.result2
}

func (fake *FakeCommand) PipelinesCallCount() int {
	fake.pipelinesMutex.RLock()
	defer fake.pipelinesMutex.RUnlock()
	return len(fake.pipelinesArgsForCall)
}

func (fake *FakeCommand) PipelinesReturns(result1 []string, result2 error) {
	fake.PipelinesStub = nil
	fake.pipelinesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) PipelinesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.PipelinesStub = nil
	if fake.pipelinesReturnsOnCall == nil {
		fake.pipelinesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.pipelinesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) GetPipeline(pipelineName string) ([]byte, error) {
	fake.getPipelineMutex.Lock()
	ret, specificReturn := fake.getPipelineReturnsOnCall[len(fake.getPipelineArgsForCall)]
	fake.getPipelineArgsForCall = append(fake.getPipelineArgsForCall, struct {
		pipelineName string
	}{pipelineName})
	fake.recordInvocation("GetPipeline", []interface{}{pipelineName})
	fake.getPipelineMutex.Unlock()
	if fake.GetPipelineStub != nil {
		return fake.GetPipelineStub(pipelineName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getPipelineReturns.result1, fake.getPipelineReturns.result2
}

func (fake *FakeCommand) GetPipelineCallCount() int {
	fake.getPipelineMutex.RLock()
	defer fake.getPipelineMutex.RUnlock()
	return len(fake.getPipelineArgsForCall)
}

func (fake *FakeCommand) GetPipelineArgsForCall(i int) string {
	fake.getPipelineMutex.RLock()
	defer fake.getPipelineMutex.RUnlock()
	return fake.getPipelineArgsForCall[i].pipelineName
}

func (fake *FakeCommand) GetPipelineReturns(result1 []byte, result2 error) {
	fake.GetPipelineStub = nil
	fake.getPipelineReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) GetPipelineReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.GetPipelineStub = nil
	if fake.getPipelineReturnsOnCall == nil {
		fake.getPipelineReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getPipelineReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) SetPipeline(pipelineName string, configFilepath string, varsFilepaths []string) ([]byte, error) {
	var varsFilepathsCopy []string
	if varsFilepaths != nil {
		varsFilepathsCopy = make([]string, len(varsFilepaths))
		copy(varsFilepathsCopy, varsFilepaths)
	}
	fake.setPipelineMutex.Lock()
	ret, specificReturn := fake.setPipelineReturnsOnCall[len(fake.setPipelineArgsForCall)]
	fake.setPipelineArgsForCall = append(fake.setPipelineArgsForCall, struct {
		pipelineName   string
		configFilepath string
		varsFilepaths  []string
	}{pipelineName, configFilepath, varsFilepathsCopy})
	fake.recordInvocation("SetPipeline", []interface{}{pipelineName, configFilepath, varsFilepathsCopy})
	fake.setPipelineMutex.Unlock()
	if fake.SetPipelineStub != nil {
		return fake.SetPipelineStub(pipelineName, configFilepath, varsFilepaths)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.setPipelineReturns.result1, fake.setPipelineReturns.result2
}

func (fake *FakeCommand) SetPipelineCallCount() int {
	fake.setPipelineMutex.RLock()
	defer fake.setPipelineMutex.RUnlock()
	return len(fake.setPipelineArgsForCall)
}

func (fake *FakeCommand) SetPipelineArgsForCall(i int) (string, string, []string) {
	fake.setPipelineMutex.RLock()
	defer fake.setPipelineMutex.RUnlock()
	return fake.setPipelineArgsForCall[i].pipelineName, fake.setPipelineArgsForCall[i].configFilepath, fake.setPipelineArgsForCall[i].varsFilepaths
}

func (fake *FakeCommand) SetPipelineReturns(result1 []byte, result2 error) {
	fake.SetPipelineStub = nil
	fake.setPipelineReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) SetPipelineReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.SetPipelineStub = nil
	if fake.setPipelineReturnsOnCall == nil {
		fake.setPipelineReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.setPipelineReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) DestroyPipeline(pipelineName string) ([]byte, error) {
	fake.destroyPipelineMutex.Lock()
	ret, specificReturn := fake.destroyPipelineReturnsOnCall[len(fake.destroyPipelineArgsForCall)]
	fake.destroyPipelineArgsForCall = append(fake.destroyPipelineArgsForCall, struct {
		pipelineName string
	}{pipelineName})
	fake.recordInvocation("DestroyPipeline", []interface{}{pipelineName})
	fake.destroyPipelineMutex.Unlock()
	if fake.DestroyPipelineStub != nil {
		return fake.DestroyPipelineStub(pipelineName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.destroyPipelineReturns.result1, fake.destroyPipelineReturns.result2
}

func (fake *FakeCommand) DestroyPipelineCallCount() int {
	fake.destroyPipelineMutex.RLock()
	defer fake.destroyPipelineMutex.RUnlock()
	return len(fake.destroyPipelineArgsForCall)
}

func (fake *FakeCommand) DestroyPipelineArgsForCall(i int) string {
	fake.destroyPipelineMutex.RLock()
	defer fake.destroyPipelineMutex.RUnlock()
	return fake.destroyPipelineArgsForCall[i].pipelineName
}

func (fake *FakeCommand) DestroyPipelineReturns(result1 []byte, result2 error) {
	fake.DestroyPipelineStub = nil
	fake.destroyPipelineReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) DestroyPipelineReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.DestroyPipelineStub = nil
	if fake.destroyPipelineReturnsOnCall == nil {
		fake.destroyPipelineReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.destroyPipelineReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) UnpausePipeline(pipelineName string) ([]byte, error) {
	fake.unpausePipelineMutex.Lock()
	ret, specificReturn := fake.unpausePipelineReturnsOnCall[len(fake.unpausePipelineArgsForCall)]
	fake.unpausePipelineArgsForCall = append(fake.unpausePipelineArgsForCall, struct {
		pipelineName string
	}{pipelineName})
	fake.recordInvocation("UnpausePipeline", []interface{}{pipelineName})
	fake.unpausePipelineMutex.Unlock()
	if fake.UnpausePipelineStub != nil {
		return fake.UnpausePipelineStub(pipelineName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.unpausePipelineReturns.result1, fake.unpausePipelineReturns.result2
}

func (fake *FakeCommand) UnpausePipelineCallCount() int {
	fake.unpausePipelineMutex.RLock()
	defer fake.unpausePipelineMutex.RUnlock()
	return len(fake.unpausePipelineArgsForCall)
}

func (fake *FakeCommand) UnpausePipelineArgsForCall(i int) string {
	fake.unpausePipelineMutex.RLock()
	defer fake.unpausePipelineMutex.RUnlock()
	return fake.unpausePipelineArgsForCall[i].pipelineName
}

func (fake *FakeCommand) UnpausePipelineReturns(result1 []byte, result2 error) {
	fake.UnpausePipelineStub = nil
	fake.unpausePipelineReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) UnpausePipelineReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.UnpausePipelineStub = nil
	if fake.unpausePipelineReturnsOnCall == nil {
		fake.unpausePipelineReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.unpausePipelineReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCommand) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	fake.pipelinesMutex.RLock()
	defer fake.pipelinesMutex.RUnlock()
	fake.getPipelineMutex.RLock()
	defer fake.getPipelineMutex.RUnlock()
	fake.setPipelineMutex.RLock()
	defer fake.setPipelineMutex.RUnlock()
	fake.destroyPipelineMutex.RLock()
	defer fake.destroyPipelineMutex.RUnlock()
	fake.unpausePipelineMutex.RLock()
	defer fake.unpausePipelineMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCommand) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fly.Command = new(FakeCommand)
